### ISSUE TITLE
Property listings page needs to be updated to read data from internal database

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#87]
Currently, the property listings page just displays data stored in the Javascript code.

It's probably best to update it so that instead it grabs the data from the database, and displays those.

The favorites feature and filter feature will probably also need this to work.

**Comment by kzcheng** [comment]
To add onto this, the same thing probably needs to be done for the detailed view of listings.

**Comment by namneyugn21** [comment]
I finished! However, I haven't check it with the current main so not merge yet...
I did make a huge change in the property database and java files too. 
Key points:
- Add street, city,  province, zip code, description
- Modify the html file of the dev/property file. 

The problem arise here is that the client NEEDS to add the image of the property manually because it is very challenging to control the image of each individual property, aka we cannot implement the upload picture functionality...

**Comment by kzcheng** [comment]
> I finished! However, I haven't check it with the current main so not merge yet... I did make a huge change in the property database and java files too. Key points:
> 
> * Add street, city,  province, zip code, description
> * Modify the html file of the dev/property file.
> 
> The problem arise here is that the client NEEDS to add the image of the property manually because it is very challenging to control the image of each individual property, aka we cannot implement the upload picture functionality...

No problem! Making changes with the database like this is good!

And yeah, for the images, it will probably be something we figure out in iteration 3.

**Comment by namneyugn21** [comment]
done!
